import { defineKit } from "../../../../../domain.js";
import { createExportResult, createImageArtifact, normalizeParameters, randomizeParameters, validateArtifactShape } from "../../../../../contracts.js";
import { createRandomStream, createSeededRandom, deriveSeed } from "../../../../../foundation/random.js";
import { imageFromSurface, surfaceFromImage } from "../../../../../foundation/raster/surface.js";
import { encodePngRgba } from "../../../../../foundation/raster/png.js";
import { rasterMetrics } from "../../../../../foundation/raster/metrics.js";
import { renderFishAsset, FISH_PALETTES, FISH_SHAPES, FISH_FINS } from "../../subject/fish/index.js";
export const KIT_ID="factory-texture-fish",DOMAIN_PATH="n:factory:texture:subject:fish";
export const parameterSchema=Object.freeze([{id:"bodyShape",label:"Body Shape",type:"select",options:FISH_SHAPES,default:"streamlined"},{id:"size",label:"Size",type:"number",minimum:0,maximum:1,default:0.55,step:0.01},{id:"palette",label:"Palette",type:"select",options:Object.keys(FISH_PALETTES),default:"reef"},{id:"direction",label:"Direction",type:"select",options:["left","right"],default:"right"},{id:"finStyle",label:"Fin Style",type:"select",options:FISH_FINS,default:"short"},{id:"detail",label:"Detail",type:"number",minimum:0,maximum:1,default:0.55,step:0.01}]);
export const manifest=defineKit({id:KIT_ID,displayName:"Fish Generator",version:"0.1.0",domainPath:DOMAIN_PATH,requires:["aquatic:fish","factory:seed","factory:artifact"],provides:["factory:generate","factory:validate","factory:variation","factory:export","artifact:image","seed:deterministic","editor:parameters","export:png","export:json"],services:["describe","generate","randomize","reroll","validate","export"],parameterSchema,editor:{title:"Fish Generator",category:"Textures",tags:["fish","aquatic","pixel-art"],preview:"image-2d",inspector:"schema",surfaces:["seed","parameters","export","diagnostics"],primary:["bodyShape","size","palette","direction","finStyle"],advanced:["detail","seed"],internal:[],randomizationGroups:[{id:"everything",label:"Everything",parameters:parameterSchema.map(p=>p.id),rerollSeed:true},{id:"form",label:"Form",parameters:["bodyShape","size","direction","finStyle"],rerollSeed:false},{id:"color",label:"Color",parameters:["palette","detail"],rerollSeed:false}]},runtime:{environments:["node","browser","worker"],permissions:[]},source:{module:"src/domains/factory/texture/kits/fish-kit/index.js",exportName:"kit"},metadata:{deterministic:true,artifactType:"image",identity:"standalone pixel-art fish subject",serviceContract:"standard-runtime-v1"}});
function entropy(){return`${Date.now()}:${Math.random()}`;}
export function generate({seed=`${KIT_ID}:001`,params={}}={}){const normalized=normalizeParameters(parameterSchema,params),result=renderFishAsset({rng:createRandomStream(seed),...normalized}),metrics=rasterMetrics(result.surface);return createImageArtifact({kitId:KIT_ID,domainPath:DOMAIN_PATH,seed,params:normalized,image:imageFromSurface(result.surface),statistics:{...metrics,...result.metrics},metadata:{generator:"fish-raster-v1"}});}
export function validate(a){const base=validateArtifactShape(a),checks=[...base.checks],add=(id,pass,detail="")=>checks.push({id,pass:Boolean(pass),detail});try{const s=surfaceFromImage(a.image),m=rasterMetrics(s);add("image:dimensions",s.width===64&&s.height===64);add("asset:transparent",a.image.transparent===true);add("asset:occupied",m.occupiedRatio>0.002&&m.occupiedRatio<0.35,m.occupiedRatio.toFixed(4));}catch(e){add("image:decode",false,e.message);}return{schemaVersion:"nexusfactory.validation-report/1",valid:checks.every(c=>c.pass),checks,deterministicHash:a?.deterministicHash??null};}
function randomOp(request={}){const seed=String(request.seed??`${KIT_ID}:001`),groupId=String(request.groupId??"everything"),group=manifest.editor.randomizationGroups.find(g=>g.id===groupId),token=request.entropy??entropy(),random=createSeededRandom(deriveSeed(seed,`range:${groupId}:${token}`)),params=randomizeParameters({schema:parameterSchema,input:request.params,parameterIds:group.parameters,random}),nextSeed=group.rerollSeed?deriveSeed(seed,`reroll:${token}`):seed;return{seed:nextSeed,params,artifact:generate({seed:nextSeed,params})};}
export const randomize=randomOp;export function reroll(request={}){const seed=String(request.seed??`${KIT_ID}:001`),nextSeed=deriveSeed(seed,`individual:${request.entropy??entropy()}`),params=normalizeParameters(parameterSchema,request.params);return{seed:nextSeed,params,artifact:generate({seed:nextSeed,params})};}
export function exportArtifact(a,format="png"){if(!validate(a).valid)throw new TypeError("Cannot export invalid fish artifact.");const suffix=a.deterministicHash.slice(-8);if(format==="png")return createExportResult({format,mimeType:"image/png",fileName:`fish-${suffix}.png`,bytes:encodePngRgba(surfaceFromImage(a.image),{scale:8})});if(format==="json")return createExportResult({format,mimeType:"application/json",fileName:`fish-${suffix}.json`,text:JSON.stringify(a,null,2)});throw new RangeError(`Unsupported fish export format: ${format}`);}
export const kit=Object.freeze({manifest,services:Object.freeze({describe:()=>structuredClone(manifest),generate,randomize,reroll,validate,export:exportArtifact})});export default kit;
