import { defineKit } from "../../../../../domain.js";
import { createExportResult, createImageArtifact, normalizeParameters, randomizeParameters, validateArtifactShape } from "../../../../../contracts.js";
import { createRandomStream, createSeededRandom, deriveSeed } from "../../../../../foundation/random.js";
import { imageFromSurface, surfaceFromImage } from "../../../../../foundation/raster/surface.js";
import { encodePngRgba } from "../../../../../foundation/raster/png.js";
import { rasterMetrics } from "../../../../../foundation/raster/metrics.js";
import { renderAquaticFloraAsset, FLORA_STYLES, FLORA_PALETTES } from "../../subject/aquatic-flora/index.js";
export const KIT_ID="factory-texture-aquatic-flora",DOMAIN_PATH="n:factory:texture:subject:aquatic-flora";
export const parameterSchema=Object.freeze([{id:"style",label:"Style",type:"select",options:FLORA_STYLES,default:"seagrass"},{id:"palette",label:"Palette",type:"select",options:Object.keys(FLORA_PALETTES),default:"green"},{id:"size",label:"Size",type:"number",minimum:0,maximum:1,default:0.55,step:0.01},{id:"density",label:"Density",type:"number",minimum:0,maximum:1,default:0.6,step:0.01},{id:"sway",label:"Sway",type:"number",minimum:0,maximum:1,default:0.4,step:0.01}]);
export const manifest=defineKit({id:KIT_ID,displayName:"Aquatic Flora Generator",version:"0.1.0",domainPath:DOMAIN_PATH,requires:["aquatic:flora","factory:seed","factory:artifact"],provides:["factory:generate","factory:validate","factory:variation","factory:export","artifact:image","seed:deterministic","editor:parameters","export:png","export:json"],services:["describe","generate","randomize","reroll","validate","export"],parameterSchema,editor:{title:"Aquatic Flora Generator",category:"Textures",tags:["flora","aquatic","pixel-art"],preview:"image-2d",inspector:"schema",surfaces:["seed","parameters","export","diagnostics"],primary:["style","palette","size","density"],advanced:["sway","seed"],internal:[],randomizationGroups:[{id:"everything",label:"Everything",parameters:parameterSchema.map(p=>p.id),rerollSeed:true},{id:"form",label:"Form",parameters:["style","size","density","sway"],rerollSeed:false},{id:"color",label:"Color",parameters:["palette"],rerollSeed:false}]},runtime:{environments:["node","browser","worker"],permissions:[]},source:{module:"src/domains/factory/texture/kits/aquatic-flora-kit/index.js",exportName:"kit"},metadata:{deterministic:true,artifactType:"image",identity:"standalone pixel-art aquatic vegetation subject",serviceContract:"standard-runtime-v1"}});
function entropy(){return`${Date.now()}:${Math.random()}`;}
export function generate({seed=`${KIT_ID}:001`,params={}}={}){const normalized=normalizeParameters(parameterSchema,params),result=renderAquaticFloraAsset({rng:createRandomStream(seed),...normalized}),metrics=rasterMetrics(result.surface);return createImageArtifact({kitId:KIT_ID,domainPath:DOMAIN_PATH,seed,params:normalized,image:imageFromSurface(result.surface),statistics:{...metrics,...result.metrics},metadata:{generator:"aquatic-flora-v1"}});}
export function validate(a){const base=validateArtifactShape(a),checks=[...base.checks],add=(id,pass,detail="")=>checks.push({id,pass:Boolean(pass),detail});try{const s=surfaceFromImage(a.image),m=rasterMetrics(s);add("image:dimensions",s.width===64&&s.height===64);add("asset:transparent",a.image.transparent===true);add("asset:occupied",m.occupiedRatio>0.002&&m.occupiedRatio<0.4,m.occupiedRatio.toFixed(4));}catch(e){add("image:decode",false,e.message);}return{schemaVersion:"nexusfactory.validation-report/1",valid:checks.every(c=>c.pass),checks,deterministicHash:a?.deterministicHash??null};}
export function randomize(request={}){const seed=String(request.seed??`${KIT_ID}:001`),groupId=String(request.groupId??"everything"),group=manifest.editor.randomizationGroups.find(g=>g.id===groupId);if(!group)throw new RangeError(`Unknown randomization group: ${groupId}`);const token=request.entropy??entropy(),random=createSeededRandom(deriveSeed(seed,`range:${groupId}:${token}`)),params=randomizeParameters({schema:parameterSchema,input:request.params,parameterIds:group.parameters,random}),nextSeed=group.rerollSeed?deriveSeed(seed,`reroll:${token}`):seed;return{seed:nextSeed,params,artifact:generate({seed:nextSeed,params})};}
export function reroll(request={}){const seed=String(request.seed??`${KIT_ID}:001`),nextSeed=deriveSeed(seed,`individual:${request.entropy??entropy()}`),params=normalizeParameters(parameterSchema,request.params);return{seed:nextSeed,params,artifact:generate({seed:nextSeed,params})};}
export function exportArtifact(a,format="png"){if(!validate(a).valid)throw new TypeError("Cannot export invalid aquatic flora artifact.");const suffix=a.deterministicHash.slice(-8);if(format==="png")return createExportResult({format,mimeType:"image/png",fileName:`aquatic-flora-${suffix}.png`,bytes:encodePngRgba(surfaceFromImage(a.image),{scale:8})});if(format==="json")return createExportResult({format,mimeType:"application/json",fileName:`aquatic-flora-${suffix}.json`,text:JSON.stringify(a,null,2)});throw new RangeError(`Unsupported aquatic flora export format: ${format}`);}
export const kit=Object.freeze({manifest,services:Object.freeze({describe:()=>structuredClone(manifest),generate,randomize,reroll,validate,export:exportArtifact})});export default kit;
