import test from "node:test";
import assert from "node:assert/strict";
import { kit } from "../src/domains/factory/object/foliage/kits/tree-kit/index.js";
const base={seed:"storybook-007",params:{maturity:.65,gravityPull:.28,upwardGrowth:.72,branchSeparation:.60,branchSpread:.62,branchDensity:.58,leaderDominance:.48,foliageDensity:.72}};

test("tree generation is deterministic and seed-sensitive",()=>{const a=kit.services.generate(base),b=kit.services.generate(base),c=kit.services.generate({...base,seed:"storybook-008"});assert.equal(a.deterministicHash,b.deterministicHash);assert.notEqual(a.deterministicHash,c.deterministicHash);assert.equal(kit.services.validate(a).valid,true);});
test("phase API is inspectable and preserves growth through bezier",()=>{let state=kit.services.createState(base);assert.deepEqual(state.completedPhases,["spec"]);state=kit.services.runPhase(state,"growth");const growth=structuredClone(state.outputs.growth);state=kit.services.runPhase(state,"bezier");assert.deepEqual(state.outputs.growth,growth);assert.equal(state.outputs.bezier.axes.length,growth.axes.length);const inspect=kit.services.inspectState(state);assert.deepEqual(inspect.completedPhases,["spec","growth","bezier"]);});
test("wood and foliage are generated in Kits with normals",()=>{const artifact=kit.services.generate(base);assert.deepEqual(artifact.meshes.map(m=>m.id),["wood-structure","foliage-pods"]);for(const mesh of artifact.meshes){assert.equal(mesh.normals.length,mesh.positions.length);assert.ok(mesh.indices.length>0);}assert.ok(artifact.metadata.foliagePods.length>=3);assert.ok(artifact.metadata.foliagePods.every(p=>p.sourceAxisId));});
test("partial foliage rerun preserves upstream state",()=>{let state=kit.services.createState(base);for(const phase of["growth","bezier","wood","foliage"])state=kit.services.runPhase(state,phase);const growth=structuredClone(state.outputs.growth),bezier=structuredClone(state.outputs.bezier),wood=structuredClone(state.outputs.wood);state=kit.services.runPhase(state,"foliage");assert.deepEqual(state.outputs.growth,growth);assert.deepEqual(state.outputs.bezier,bezier);assert.deepEqual(state.outputs.wood,wood);assert.equal(state.artifact,null);});
test("range randomization and seed reroll are separate",()=>{const randomized=kit.services.randomize({...base,groupId:"growth",entropy:"fixed"});assert.equal(randomized.seed,base.seed);assert.notDeepEqual(randomized.params,base.params);const rerolled=kit.services.reroll({...base,entropy:"fixed"});assert.notEqual(rerolled.seed,base.seed);assert.deepEqual(rerolled.params,base.params);});
test("export returns self-describing result and GLB includes normals",()=>{const artifact=kit.services.generate(base),result=kit.services.export(artifact,"glb");assert.equal(result.schemaVersion,"nexusfactory.export-result/1");assert.equal(result.mimeType,"model/gltf-binary");assert.ok(result.fileName.endsWith(".glb"));const view=new DataView(result.bytes.buffer,result.bytes.byteOffset,result.bytes.byteLength);assert.equal(view.getUint32(0,true),0x46546c67);const jsonLength=view.getUint32(12,true);const text=new TextDecoder().decode(result.bytes.slice(20,20+jsonLength)).trim();const gltf=JSON.parse(text);assert.ok(gltf.meshes.every(m=>m.primitives[0].attributes.NORMAL!==undefined));});
test("phase prerequisites are enforced",()=>{const state=kit.services.createState(base);assert.throws(()=>kit.services.runPhase(state,"bezier"),/growth is required/);});
