import { mkdir,writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { kit,ARCHETYPES } from '../../src/domains/factory/object/creature/kits/horror-kit/index.js';
import { kit as corridor } from '../../src/domains/factory/object/structure/kits/liminal-kit/index.js';
import { kit as distressed } from '../../src/domains/factory/material/procedural/kits/distressed-kit/index.js';
const output=resolve(process.argv[2]??'validation/horror/latest');await mkdir(output,{recursive:true});const start=performance.now(),runs=[];
for(const archetype of ARCHETYPES){const t=performance.now(),request={seed:'wrong-floor-review-1',params:{archetype,distortion:.75,detail:24}},a=kit.services.generate(request),again=kit.services.generate(request),validation=kit.services.validate(a),exported=kit.services.export(a,'glb');await writeFile(resolve(output,archetype+'.glb'),exported.bytes);await writeFile(resolve(output,archetype+'.json'),JSON.stringify(a));runs.push({archetype,input:request,signature:a.deterministicHash,repeatSignature:again.deterministicHash,deterministic:a.deterministicHash===again.deterministicHash,statistics:a.statistics,stages:a.metadata.stageRecords,validation,exports:[archetype+'.glb',archetype+'.json'],elapsedMs:performance.now()-t});}
for(const [id,k]of [['corridor',corridor],['distressed',distressed]]){const a=k.services.generate({seed:'wrong-floor-review-1'});runs.push({id,signature:a.deterministicHash,validation:k.services.validate(a),statistics:a.statistics});}
const report={runId:'horror-review-1',factoryId:kit.manifest.id,parameters:runs.map(r=>r.input?.params??{}),seed:'wrong-floor-review-1',stages:runs.flatMap(r=>r.stages??[]),artifactSignatures:runs.map(r=>r.signature),validation:runs.map(r=>r.validation),exports:runs.flatMap(r=>r.exports??[]),factoryVersion:kit.manifest.version,synthetic:true,environment:{node:process.version},runs,visualCaptures:[],visualReview:'pending separate browser captures',warnings:['Static meshes expose animation roles; game owns temporal deformation and gameplay.','Technical validity does not establish subjective horror or production quality.'],errors:[],elapsedMs:performance.now()-start,status:runs.every(r=>r.validation.valid&&r.deterministic!==false)?'partial':'fail'};await writeFile(resolve(output,'run-report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({output,status:report.status,runs:runs.length,elapsedMs:report.elapsedMs}));if(report.status==='fail')process.exitCode=1;
