import * as THREE from 'three';
import { kit } from '../../src/domains/factory/object/creature/kits/horror-kit/index.js';
const scene=new THREE.Scene();scene.background=new THREE.Color('#202127');
const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(1);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.5;document.body.append(renderer.domElement);
const camera=new THREE.PerspectiveCamera(36,innerWidth/innerHeight,.01,100);scene.add(new THREE.HemisphereLight(0xa7b4c7,0x302018,2));for(const [x,y,z,c,intensity]of [[3,5,5,0xffd9b5,60],[-3,3,1,0x748bac,35],[0,4,-3,0xe1b385,50]]){const l=new THREE.PointLight(c,intensity);l.position.set(x,y,z);scene.add(l);}
let group=new THREE.Group(),artifact,angle=.15,revision=0;scene.add(group);
function regenerate(input){scene.remove(group);group.traverse(o=>{o.geometry?.dispose();o.material?.dispose();});group=new THREE.Group();scene.add(group);artifact=kit.services.generate(input??{seed:document.querySelector('#seed').value,params:{archetype:document.querySelector('#archetype').value,distortion:Number(document.querySelector('#distortion').value)}});
 for(const m of artifact.meshes){const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(m.positions,3));g.setAttribute('normal',new THREE.Float32BufferAttribute(m.normals,3));g.setAttribute('color',new THREE.Float32BufferAttribute(m.colors,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(m.uvs,2));g.setIndex(m.indices);const p=artifact.materials[m.material],material=new THREE.MeshStandardMaterial({color:new THREE.Color(...p.baseColorFactor.slice(0,3)),roughness:p.roughnessFactor,metalness:p.metallicFactor,vertexColors:true,side:THREE.DoubleSide,emissive:new THREE.Color(...(p.emissiveFactor??[0,0,0]))});const mesh=new THREE.Mesh(g,material);mesh.name=m.id;group.add(mesh);}
 const height=artifact.bounds.size[1],width=artifact.bounds.size[0],distance=Math.max(height,width)*2.1;camera.position.set(Math.sin(angle)*distance,height*.56,Math.cos(angle)*distance);camera.lookAt(0,height*.48,0);renderer.render(scene,camera);document.querySelector('#report').textContent=JSON.stringify({signature:artifact.deterministicHash,triangles:artifact.statistics.triangleCount,valid:kit.services.validate(artifact).valid},null,2);return artifact.deterministicHash;
}
document.querySelector('#generate').onclick=()=>regenerate();document.querySelector('#reroll').onclick=()=>{document.querySelector('#seed').value+=':'+ ++revision;regenerate();};document.querySelector('#export').onclick=()=>{const out=kit.services.export(artifact,'glb'),url=URL.createObjectURL(new Blob([out.bytes],{type:out.mimeType})),a=document.createElement('a');a.href=url;a.download=out.fileName;a.click();URL.revokeObjectURL(url);};
window.horrorHarness={generate:regenerate,inspect:()=>({hash:artifact.deterministicHash,validation:kit.services.validate(artifact),stats:artifact.statistics}),orbit:a=>{angle=a;return regenerate({seed:artifact.seed,params:artifact.params});}};
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);renderer.render(scene,camera);});regenerate();
