import { createExportResult, createGenerationState, createImageArtifact, inspectGenerationState, normalizeParameters, randomizeParameters, validateArtifactShape } from "../../../../contracts.js";
import { createSeededRandom, deriveSeed } from "../../../../foundation/random.js";
import { surfaceFromImage } from "../../../../foundation/raster/surface.js";
import { encodePngRgba } from "../../../../foundation/raster/png.js";
import { buildTerrain, buildEnvironment, buildPopulation, buildPlacement, buildSubjects, buildEffects, composeAquaticImage } from "./pipeline.js";
export const PHASE_ORDER=Object.freeze(["terrain","environment","population","placement","subjects","effects","compose","artifact","validate"]);
export const PHASE_DESCRIPTORS=Object.freeze([
{id:"terrain",requires:[],outputSchema:"nexusfactory.scene-terrain-profile/1"},{id:"environment",requires:[],outputSchema:"nexusfactory.aquatic-environment/1"},{id:"population",requires:[],outputSchema:"nexusfactory.aquatic-population/1"},{id:"placement",requires:["terrain","population"],outputSchema:"nexusfactory.scene-placement/1"},{id:"subjects",requires:["placement"],outputSchema:"nexusfactory.aquatic-subject-set/1"},{id:"effects",requires:["population"],outputSchema:"nexusfactory.aquatic-effects/1"},{id:"compose",requires:["terrain","environment","population","subjects","effects"],outputSchema:"nexusfactory.image/1"},{id:"artifact",requires:["compose"],outputSchema:"nexusfactory.artifact/1"},{id:"validate",requires:["artifact"],outputSchema:"nexusfactory.validation-report/1"}
]);
function entropy(){if(globalThis.crypto?.getRandomValues){const a=new Uint32Array(2);globalThis.crypto.getRandomValues(a);return`${a[0]}:${a[1]}`;}return`${Date.now()}:${Math.random()}`;}
export function createAquaticSceneRuntime({manifest,parameterSchema,policy,fileStem}){
 const seedOf=(request={})=>{const seed=String(request.seed??`${manifest.id}:001`).trim();if(!seed)throw new TypeError(`${manifest.displayName} requires a non-empty seed.`);return seed;};
 const requirePhase=(state,phase)=>{if(!state.completedPhases.includes(phase))throw new Error(`Phase ${phase} is required.`);};
 const invalidateAfter=(state,phase)=>{const index=PHASE_ORDER.indexOf(phase);for(const later of PHASE_ORDER.slice(index+1)){delete state.outputs[later];if(later==="artifact")state.artifact=null;if(later==="validate")state.validation=null;state.completedPhases=state.completedPhases.filter(p=>p!==later);}};
 function validate(artifact){const base=validateArtifactShape(artifact),checks=[...base.checks],add=(id,pass,detail="")=>checks.push({id,pass:Boolean(pass),detail});try{const surface=surfaceFromImage(artifact.image);add("image:dimensions",surface.width===128&&surface.height===128,`${surface.width}x${surface.height}`);add("scene:opaque",artifact.image.transparent===false);add("scene:corals",Number(artifact.statistics?.coralCount)>0,String(artifact.statistics?.coralCount??0));add("scene:fish",Number(artifact.statistics?.fishCount)>=3,String(artifact.statistics?.fishCount??0));}catch(error){add("image:decode",false,error.message);}return{schemaVersion:"nexusfactory.validation-report/1",valid:checks.every(c=>c.pass),checks,deterministicHash:artifact?.deterministicHash??null};}
 function createState(request={}){const seed=seedOf(request),params=normalizeParameters(parameterSchema,request.params);return createGenerationState({kitId:manifest.id,domainPath:manifest.domainPath,seed,params,phaseOrder:PHASE_ORDER});}
 function runPhase(inputState,phase){const state=structuredClone(inputState);if(state?.kitId!==manifest.id)throw new TypeError("Generation state belongs to another kit.");if(!PHASE_ORDER.includes(phase))throw new RangeError(`Unsupported phase: ${phase}`);invalidateAfter(state,phase);if(phase==="terrain")state.outputs.terrain=buildTerrain(state.seed,state.params,policy);if(phase==="environment")state.outputs.environment=buildEnvironment(state.params);if(phase==="population")state.outputs.population=buildPopulation(state.params,policy);if(phase==="placement"){requirePhase(state,"terrain");requirePhase(state,"population");state.outputs.placement=buildPlacement(state.seed,state.params,state.outputs.terrain,state.outputs.population,policy);}if(phase==="subjects"){requirePhase(state,"placement");state.outputs.subjects=buildSubjects(state.seed,state.params,state.outputs.placement);}if(phase==="effects"){requirePhase(state,"population");state.outputs.effects=buildEffects(state.outputs.population);}if(phase==="compose"){for(const dep of ["terrain","environment","population","subjects","effects"])requirePhase(state,dep);state.outputs.compose=composeAquaticImage(state.seed,state.params,state.outputs.terrain,state.outputs.environment,state.outputs.population,state.outputs.subjects,state.outputs.effects,policy);}if(phase==="artifact"){requirePhase(state,"compose");state.artifact=createImageArtifact({kitId:manifest.id,domainPath:manifest.domainPath,seed:state.seed,params:state.params,image:state.outputs.compose,statistics:{coralCount:state.outputs.subjects.corals.length,fishCount:state.outputs.population.fishCount,floraCount:state.outputs.population.floraCount,layerCounts:Object.fromEntries(state.outputs.placement.layers.map(l=>[l.id,l.count]))},metadata:{composition:policy.id,phaseOrder:PHASE_ORDER}});state.outputs.artifact=state.artifact;}if(phase==="validate"){requirePhase(state,"artifact");state.validation=validate(state.artifact);state.outputs.validate=state.validation;if(!state.validation.valid)throw new Error(`${manifest.displayName} validation failed.`);}state.completedPhases=[...state.completedPhases.filter(p=>p!==phase),phase];return state;}
 function generate(request={}){let state=createState(request);for(const phase of PHASE_ORDER)state=runPhase(state,phase);return state.artifact;}
 function randomize(request={}){const seed=seedOf(request),groupId=String(request.groupId??"everything"),group=manifest.editor.randomizationGroups.find(g=>g.id===groupId);if(!group)throw new RangeError(`Unknown randomization group: ${groupId}`);const token=request.entropy??entropy(),random=createSeededRandom(deriveSeed(seed,`range:${groupId}:${token}`)),params=randomizeParameters({schema:parameterSchema,input:request.params,parameterIds:group.parameters,random}),nextSeed=group.rerollSeed?deriveSeed(seed,`reroll:${token}`):seed;return{seed:nextSeed,params,artifact:generate({seed:nextSeed,params})};}
 function reroll(request={}){const seed=seedOf(request),nextSeed=deriveSeed(seed,`individual:${request.entropy??entropy()}`),params=normalizeParameters(parameterSchema,request.params);return{seed:nextSeed,params,artifact:generate({seed:nextSeed,params})};}
 function exportArtifact(artifact,format="png"){if(!validate(artifact).valid)throw new TypeError(`Cannot export invalid ${manifest.displayName} artifact.`);const suffix=artifact.deterministicHash.slice(-8);if(format==="png")return createExportResult({format,mimeType:"image/png",fileName:`${fileStem}-${suffix}.png`,bytes:encodePngRgba(surfaceFromImage(artifact.image),{scale:8})});if(format==="json")return createExportResult({format,mimeType:"application/json",fileName:`${fileStem}-${suffix}.json`,text:JSON.stringify(artifact,null,2)});throw new RangeError(`Unsupported ${manifest.displayName} export format: ${format}`);}
 return Object.freeze({createState,inspectState:inspectGenerationState,runPhase,generate,randomize,reroll,validate,export:exportArtifact});
}
