import { color } from "./surface.js";
export function createMask(width,height){ return {width,height,data:new Uint8Array(width*height)}; }
export function maskPixel(mask,x,y,value=1){ x=Math.round(x);y=Math.round(y); if(x<0||y<0||x>=mask.width||y>=mask.height)return; mask.data[y*mask.width+x]=value; }
export function maskRect(mask,x,y,w,h,value=1){ x=Math.round(x);y=Math.round(y);w=Math.max(1,Math.round(w));h=Math.max(1,Math.round(h)); for(let yy=y;yy<y+h;yy++)for(let xx=x;xx<x+w;xx++)maskPixel(mask,xx,yy,value); }
export function maskCircle(mask,cx,cy,r,value=1){ r=Math.max(0,Math.round(r)); for(let y=-r;y<=r;y++)for(let x=-r;x<=r;x++)if(x*x+y*y<=r*r)maskPixel(mask,cx+x,cy+y,value); }
export function maskEllipse(mask,cx,cy,rx,ry,value=1){ rx=Math.max(1,Math.round(rx));ry=Math.max(1,Math.round(ry)); for(let y=-ry;y<=ry;y++)for(let x=-rx;x<=rx;x++)if((x*x)/(rx*rx)+(y*y)/(ry*ry)<=1)maskPixel(mask,cx+x,cy+y,value); }
export function maskLine(mask,x0,y0,x1,y1,radius=0,value=1){ const dx=x1-x0,dy=y1-y0,steps=Math.max(Math.abs(dx),Math.abs(dy),1); for(let i=0;i<=steps;i++){ const t=i/steps,x=x0+dx*t,y=y0+dy*t; if(radius>0)maskCircle(mask,x,y,radius,value);else maskPixel(mask,x,y,value); } }
export function maskPolyline(mask,points,radius=0,value=1){ for(let i=1;i<points.length;i++)maskLine(mask,points[i-1][0],points[i-1][1],points[i][0],points[i][1],radius,value); }
export function cleanMask(mask,{minNeighbors=1,passes=1}={}){ for(let pass=0;pass<passes;pass++){ const next=mask.data.slice(); for(let y=1;y<mask.height-1;y++)for(let x=1;x<mask.width-1;x++){ const i=y*mask.width+x; if(!mask.data[i])continue; let neighbors=0; for(let oy=-1;oy<=1;oy++)for(let ox=-1;ox<=1;ox++)if((ox||oy)&&mask.data[(y+oy)*mask.width+x+ox])neighbors++; if(neighbors<minNeighbors)next[i]=0; } mask.data.set(next); } return mask; }
export function fillRect(surface,x,y,w,h,rgba){ const c=color(rgba); for(let yy=Math.round(y);yy<Math.round(y+h);yy++)for(let xx=Math.round(x);xx<Math.round(x+w);xx++)surface.setPixel(xx,yy,c); }
export function drawLine(surface,x0,y0,x1,y1,rgba,radius=0){ const c=color(rgba),dx=x1-x0,dy=y1-y0,steps=Math.max(Math.abs(dx),Math.abs(dy),1); for(let i=0;i<=steps;i++){const t=i/steps,x=Math.round(x0+dx*t),y=Math.round(y0+dy*t); if(radius<=0)surface.setPixel(x,y,c); else for(let oy=-radius;oy<=radius;oy++)for(let ox=-radius;ox<=radius;ox++)if(ox*ox+oy*oy<=radius*radius)surface.setPixel(x+ox,y+oy,c);} }
export function blitNearest(target,source,{x=0,y=0,scale=1,opacity=1}={}){ const s=Math.max(0.01,Number(scale)); const outW=Math.max(1,Math.round(source.width*s)),outH=Math.max(1,Math.round(source.height*s)); for(let oy=0;oy<outH;oy++)for(let ox=0;ox<outW;ox++){ const sx=Math.min(source.width-1,Math.floor(ox/s)),sy=Math.min(source.height-1,Math.floor(oy/s)),si=(sy*source.width+sx)*4,a=(source.pixels[si+3]/255)*opacity; if(a<=0)continue; const tx=Math.round(x+ox),ty=Math.round(y+oy); if(tx<0||ty<0||tx>=target.width||ty>=target.height)continue; const ti=(ty*target.width+tx)*4,ia=1-a; target.pixels[ti]=Math.round(source.pixels[si]*a+target.pixels[ti]*ia); target.pixels[ti+1]=Math.round(source.pixels[si+1]*a+target.pixels[ti+1]*ia); target.pixels[ti+2]=Math.round(source.pixels[si+2]*a+target.pixels[ti+2]*ia); target.pixels[ti+3]=Math.min(255,Math.round(source.pixels[si+3]*opacity+target.pixels[ti+3]*ia)); } }
