import { defineKit } from "../../../../../domain.js";
import { createExportResult, createImageArtifact, normalizeParameters, randomizeParameters, validateArtifactShape } from "../../../../../contracts.js";
import { createRandomStream, createSeededRandom, deriveSeed } from "../../../../../foundation/random.js";
import { imageFromSurface, surfaceFromImage } from "../../../../../foundation/raster/surface.js";
import { encodePngRgba } from "../../../../../foundation/raster/png.js";
import { rasterMetrics, connectedComponentsAlpha } from "../../../../../foundation/raster/metrics.js";
import { renderCoralMorphology, SPECIES, PALETTES } from "../../subject/coral/index.js";
export const KIT_ID="factory-texture-coral",DOMAIN_PATH="n:factory:texture:subject:coral";
export const parameterSchema=Object.freeze([
{id:"species",label:"Species",type:"select",options:SPECIES.map(e=>e.id),default:"staghorn"},{id:"palette",label:"Coral Palette",type:"select",options:Object.keys(PALETTES),default:"pink"},{id:"size",label:"Size",type:"number",minimum:0,maximum:1,default:0.55,step:0.01},{id:"density",label:"Density",type:"number",minimum:0,maximum:1,default:0.58,step:0.01},{id:"asymmetry",label:"Asymmetry",type:"number",minimum:0,maximum:1,default:0.28,step:0.01},{id:"highlight",label:"Highlight",type:"number",minimum:0,maximum:1,default:0.55,step:0.01}
]);
export const manifest=defineKit({id:KIT_ID,displayName:"Coral Generator",version:"0.2.0",domainPath:DOMAIN_PATH,requires:["aquatic:coral","factory:seed","factory:artifact"],provides:["factory:generate","factory:validate","factory:variation","factory:export","artifact:image","seed:deterministic","editor:parameters","export:png","export:json"],services:["describe","generate","randomize","reroll","validate","export"],parameterSchema,editor:{title:"Coral Generator",category:"Textures",tags:["coral","pixel-art","procedural"],preview:"image-2d",inspector:"schema",surfaces:["seed","parameters","export","diagnostics"],primary:["species","palette","size","density","asymmetry"],advanced:["highlight","seed"],internal:[],randomizationGroups:[{id:"everything",label:"Everything",parameters:["species","palette","size","density","asymmetry","highlight"],rerollSeed:true},{id:"form",label:"Form",parameters:["species","size","density","asymmetry"],rerollSeed:false},{id:"color",label:"Color",parameters:["palette","highlight"],rerollSeed:false}]},runtime:{environments:["node","browser","worker"],permissions:[]},source:{module:"src/domains/factory/texture/kits/coral-kit/index.js",exportName:"kit"},metadata:{deterministic:true,artifactType:"image",identity:"standalone pixel-art coral generated from shared coral morphology",species:SPECIES.map(({id,common,scientific,form})=>({id,common,scientific,form})),serviceContract:"standard-runtime-v1"}});
function entropy(){if(globalThis.crypto?.getRandomValues){const a=new Uint32Array(2);globalThis.crypto.getRandomValues(a);return`${a[0]}:${a[1]}`;}return`${Date.now()}:${Math.random()}`;}
export function generate({seed=`${KIT_ID}:001`,params={}}={}){const normalized=normalizeParameters(parameterSchema,params),rng=createRandomStream(seed),palette=PALETTES[normalized.palette]??PALETTES.gold,result=renderCoralMorphology({rng:rng.fork("asset").fork("morphology"),width:96,height:96,speciesId:normalized.species,size:normalized.size,density:normalized.density,asymmetry:normalized.asymmetry,palette,highlight:normalized.highlight,seed:String(seed),withBase:true}),metrics=rasterMetrics(result.surface);return createImageArtifact({kitId:KIT_ID,domainPath:DOMAIN_PATH,seed,params:normalized,image:imageFromSurface(result.surface),statistics:{...metrics,connectedComponents:connectedComponentsAlpha(result.surface)},metadata:{resolvedSpecies:normalized.species,generator:"coral-morphology-v2"}});}
export function validate(artifact){const base=validateArtifactShape(artifact),checks=[...base.checks],add=(id,pass,detail="")=>checks.push({id,pass:Boolean(pass),detail});try{const s=surfaceFromImage(artifact.image),m=rasterMetrics(s);add("image:dimensions",s.width===96&&s.height===96,`${s.width}x${s.height}`);add("asset:transparent",artifact.image.transparent===true);add("asset:occupied",m.occupiedRatio>0.015&&m.occupiedRatio<0.55,m.occupiedRatio.toFixed(4));add("asset:connected",connectedComponentsAlpha(s)<=6,String(connectedComponentsAlpha(s)));}catch(error){add("image:decode",false,error.message);}return{schemaVersion:"nexusfactory.validation-report/1",valid:checks.every(c=>c.pass),checks,deterministicHash:artifact?.deterministicHash??null};}
export function randomize(request={}){const seed=String(request.seed??`${KIT_ID}:001`),groupId=String(request.groupId??"everything"),group=manifest.editor.randomizationGroups.find(g=>g.id===groupId);if(!group)throw new RangeError(`Unknown randomization group: ${groupId}`);const token=request.entropy??entropy(),random=createSeededRandom(deriveSeed(seed,`range:${groupId}:${token}`)),params=randomizeParameters({schema:parameterSchema,input:request.params,parameterIds:group.parameters,random}),nextSeed=group.rerollSeed?deriveSeed(seed,`reroll:${token}`):seed;return{seed:nextSeed,params,artifact:generate({seed:nextSeed,params})};}
export function reroll(request={}){const seed=String(request.seed??`${KIT_ID}:001`),token=request.entropy??entropy(),nextSeed=deriveSeed(seed,`individual:${token}`),params=normalizeParameters(parameterSchema,request.params);return{seed:nextSeed,params,artifact:generate({seed:nextSeed,params})};}
export function exportArtifact(artifact,format="png"){const result=validate(artifact);if(!result.valid)throw new TypeError("Cannot export invalid coral artifact.");const suffix=artifact.deterministicHash.slice(-8);if(format==="png")return createExportResult({format,mimeType:"image/png",fileName:`coral-${suffix}.png`,bytes:encodePngRgba(surfaceFromImage(artifact.image),{scale:8})});if(format==="json")return createExportResult({format,mimeType:"application/json",fileName:`coral-${suffix}.json`,text:JSON.stringify(artifact,null,2)});throw new RangeError(`Unsupported coral export format: ${format}`);}
export const kit=Object.freeze({manifest,services:Object.freeze({describe:()=>structuredClone(manifest),generate,randomize,reroll,validate,export:exportArtifact})});export default kit;
