import { defineDomain } from "../../../../../../domain.js";
import { add, computeMeshNormals, cross, dot, mergeMeshes, normalize, scale, sub } from "../../../../../../foundation/geometry.js";
export const TREE_WOOD_SCHEMA="nexusfactory.tree-wood/1";
export const treeWoodDomain=defineDomain({id:"factory-object-foliage-tree-wood-domain",domainPath:"n:factory:object:foliage:tree:wood",parentDomainPath:"n:factory:object:foliage:tree",requires:["factory:object:foliage:tree","tree:curve:bezier"],provides:["tree:wood"],owns:["tapered tree tubes","tube frames","wood normals"],doesNotOwn:["growth semantics","foliage geometry","viewport shading"],services:["tree-wood-mesh"]});
function projectPerpendicular(v,t){return sub(v,scale(t,dot(v,t)));}
function safeNormal(v,fallback){try{return normalize(v);}catch{return fallback;}}
function tubeMesh(axis){const points=axis.sampledPoints,segments=axis.kind==="trunk"?10:axis.kind==="leader"?8:7,mesh={id:`wood-${axis.id}`,material:"bark",positions:[],indices:[]};let normal=null,binormal=null;for(let i=0;i<points.length;i++){const prev=points[Math.max(0,i-1)],next=points[Math.min(points.length-1,i+1)],t=safeNormal(sub(next,prev),[0,1,0]);if(!normal){const ref=Math.abs(t[1])<.88?[0,1,0]:[1,0,0];normal=safeNormal(cross(t,ref),[1,0,0]);}else normal=safeNormal(projectPerpendicular(normal,t),normal);binormal=safeNormal(cross(t,normal),[0,0,1]);const u=i/Math.max(1,points.length-1),radius=axis.radiusStart*(1-u)+axis.radiusEnd*u;for(let s=0;s<segments;s++){const a=Math.PI*2*s/segments,radial=add(scale(normal,Math.cos(a)*radius),scale(binormal,Math.sin(a)*radius)),p=add(points[i],radial);mesh.positions.push(...p);}}
for(let i=0;i<points.length-1;i++)for(let s=0;s<segments;s++){const n=(s+1)%segments,a=i*segments+s,b=(i+1)*segments+s,c=(i+1)*segments+n,d=i*segments+n;mesh.indices.push(a,b,c,a,c,d);}if(axis.kind==="trunk"){const centerIndex=mesh.positions.length/3;mesh.positions.push(...points[0]);for(let s=0;s<segments;s++){const n=(s+1)%segments;mesh.indices.push(centerIndex,n,s);}}const tipIndex=mesh.positions.length/3;mesh.positions.push(...points.at(-1));const ring=(points.length-1)*segments;for(let s=0;s<segments;s++){const n=(s+1)%segments;mesh.indices.push(tipIndex,ring+s,ring+n);}mesh.normals=computeMeshNormals(mesh);return mesh;}
export function generateTreeWood({bezier}){const parts=bezier.axes.map(tubeMesh),mesh=mergeMeshes("wood-structure",parts,"bark");mesh.normals=computeMeshNormals(mesh);return{schemaVersion:TREE_WOOD_SCHEMA,mesh,axisCount:bezier.axes.length,provenance:{algorithm:"bezier-tube-v1",frame:"transported"}};}
