import { createArtifact, createExportResult, createGenerationState, inspectGenerationState, normalizeParameters, randomizeParameters, validateArtifactShape } from "../../../../../../contracts.js";
import { createSeededRandom, deriveSeed } from "../../../../../../foundation/random.js";
import { exportArtifactGlb } from "../../../../../../foundation/glb.js";
import { generateTreeGrowth } from "../../tree/growth/index.js";
import { fitTreeBezier } from "../../tree/curve/bezier/index.js";
import { generateTreeWood } from "../../tree/wood/index.js";
import { generateTreeCrown } from "../../tree/crown/index.js";
import { PHASE_ORDER, parameterSchema } from "./config.js";
import { storybookClayProfile } from "./profiles/storybook-clay.js";
import { manifest } from "./spec.js";
export { manifest };

function generationSeed(request={}){const seed=String(request.seed??`${manifest.id}:001`).trim();if(!seed)throw new TypeError("Tree generation requires a non-empty seed.");return seed;}
export function createState(request={}){const seed=generationSeed(request),params=normalizeParameters(parameterSchema,request.params);return createGenerationState({kitId:manifest.id,domainPath:manifest.domainPath,seed,params,phaseOrder:PHASE_ORDER});}
export function inspectState(state){return inspectGenerationState(state);}
function requirePhase(state,phase){if(!state.completedPhases.includes(phase))throw new Error(`Phase ${phase} is required.`);}
function mark(state,phase){state.completedPhases=[...state.completedPhases.filter(p=>p!==phase),phase];}
function invalidateAfter(state,phase){const index=PHASE_ORDER.indexOf(phase);for(const later of PHASE_ORDER.slice(index+1)){delete state.outputs[later];if(later==="artifact")state.artifact=null;if(later==="validate")state.validation=null;state.completedPhases=state.completedPhases.filter(p=>p!==later);}}
function composeArtifact(state){return createArtifact({kitId:manifest.id,domainPath:manifest.domainPath,seed:state.seed,params:state.params,meshes:[state.outputs.wood.mesh,state.outputs.foliage.mesh],materials:storybookClayProfile.materials,metadata:{profile:storybookClayProfile.id,renderHints:storybookClayProfile.renderHints,growth:{leaderCount:state.outputs.growth.leaderCount,branchCount:state.outputs.growth.branchCount,terminalRegions:state.outputs.growth.terminalRegions},foliagePods:state.outputs.foliage.pods,phaseOrder:PHASE_ORDER,submeshes:["wood-structure","foliage-pods"]}});}
export function runPhase(inputState,phase){const state=structuredClone(inputState);if(state?.kitId!==manifest.id)throw new TypeError("Tree state belongs to another kit.");if(!PHASE_ORDER.includes(phase))throw new RangeError(`Unsupported tree phase: ${phase}`);invalidateAfter(state,phase);if(phase==="growth")state.outputs.growth=generateTreeGrowth({seed:state.seed,params:state.params});if(phase==="bezier"){requirePhase(state,"growth");state.outputs.bezier=fitTreeBezier({growth:state.outputs.growth,params:state.params});}if(phase==="wood"){requirePhase(state,"bezier");state.outputs.wood=generateTreeWood({bezier:state.outputs.bezier});}if(phase==="foliage"){requirePhase(state,"growth");requirePhase(state,"bezier");state.outputs.foliage=generateTreeCrown({seed:state.seed,growth:state.outputs.growth,bezier:state.outputs.bezier,params:state.params});}if(phase==="artifact"){requirePhase(state,"wood");requirePhase(state,"foliage");state.artifact=composeArtifact(state);state.outputs.artifact={deterministicHash:state.artifact.deterministicHash};}if(phase==="validate"){requirePhase(state,"artifact");state.validation=validate(state.artifact);state.outputs.validate=state.validation;if(!state.validation.valid)throw new Error(`Tree validation failed: ${state.validation.checks.filter(c=>!c.pass).map(c=>c.id).join(", ")}`);}mark(state,phase);return state;}
export function generate(request={}){let state=createState(request);for(const phase of PHASE_ORDER)state=runPhase(state,phase);return state.artifact;}
function entropyValue(){if(globalThis.crypto?.getRandomValues){const a=new Uint32Array(2);globalThis.crypto.getRandomValues(a);return `${a[0]}:${a[1]}`;}return `${Date.now()}:${Math.random()}`;}
export function randomize(request={}){const seed=generationSeed(request),groupId=String(request.groupId??"everything"),group=manifest.editor.randomizationGroups.find(g=>g.id===groupId);if(!group)throw new RangeError(`Unknown randomization group: ${groupId}`);const entropy=request.entropy??entropyValue(),random=createSeededRandom(deriveSeed(seed,`range:${groupId}:${entropy}`)),params=randomizeParameters({schema:parameterSchema,input:request.params,parameterIds:group.parameters,random}),nextSeed=group.rerollSeed?deriveSeed(seed,`reroll:${entropy}`):seed;return{seed:nextSeed,params,artifact:generate({seed:nextSeed,params})};}
export function reroll(request={}){const seed=generationSeed(request),entropy=request.entropy??entropyValue(),nextSeed=deriveSeed(seed,`individual:${entropy}`),params=normalizeParameters(parameterSchema,request.params);return{seed:nextSeed,params,artifact:generate({seed:nextSeed,params})};}
export function validate(artifact){const base=validateArtifactShape(artifact),checks=[...base.checks],meshes=artifact?.meshes??[],ids=new Set(meshes.map(m=>m.id)),wood=meshes.find(m=>m.id==="wood-structure"),foliage=meshes.find(m=>m.id==="foliage-pods"),pods=artifact?.metadata?.foliagePods??[],leaders=Number(artifact?.metadata?.growth?.leaderCount??0),size=artifact?.bounds?.size??[0,0,0];checks.push({id:"structure:two-submeshes",pass:meshes.length===2&&ids.has("wood-structure")&&ids.has("foliage-pods"),detail:[...ids].join(",")},{id:"wood:triangles",pass:(wood?.indices?.length??0)>=60,detail:String((wood?.indices?.length??0)/3)},{id:"foliage:leader-derived",pass:pods.length===leaders+1&&pods.every(p=>p.sourceAxisId),detail:`pods=${pods.length} leaders=${leaders}`},{id:"foliage:multiple-pods",pass:pods.length>=3&&pods.length<=5,detail:String(pods.length)},{id:"bounds:healthy",pass:size.every(v=>Number.isFinite(v)&&v>0),detail:size.map(v=>v.toFixed(2)).join("x")},{id:"normals:owned-by-kits",pass:meshes.every(m=>Array.isArray(m.normals)&&m.normals.length===m.positions.length),detail:"provided"});return{valid:checks.every(c=>c.pass),checks,deterministicHash:artifact?.deterministicHash??null};}
export function exportArtifact(artifact,format="glb"){const validation=validate(artifact);if(!validation.valid)throw new TypeError("Cannot export invalid tree artifact.");const stem=`storybook-tree-${artifact.deterministicHash.slice(-8)}`;if(format==="glb")return createExportResult({format,mimeType:"model/gltf-binary",fileName:`${stem}.glb`,bytes:exportArtifactGlb(artifact)});if(format==="json")return createExportResult({format,mimeType:"application/json",fileName:`${stem}.json`,text:JSON.stringify(artifact,null,2)});throw new RangeError(`Unsupported tree export format: ${format}`);}
export const kit=Object.freeze({manifest,services:Object.freeze({describe:()=>structuredClone(manifest),createState,inspectState,runPhase,generate,randomize,reroll,validate,export:exportArtifact})});
export default kit;
